### ISSUE TITLE
UX for loading data/spreads

### ISSUE THREAD

**Issue by mcorrell** [mcorrell/vis-tarot#1]
Datasets in the "data" folder should appear on a dropdown. Loading one should determine which dataset is active.

Similarly, there should be a dropdown for different card spreads. Loading one should swap between the card layouts in main.js

**Comment by mcnuttandrew** [comment]
I'm going to go ahead and claim this one! I'll try to pull together some sort of draft in the next day or so

**Comment by mcnuttandrew** [comment]
@mcorrell do you have any visual references for the look of the tool you are interested in using? Or are we aiming for close alignment with the vibe of general va tools?

**Comment by mcorrell** [comment]
I was envisioning something sort of minimal and monochrome for the cards themselves, with mostly white and 333333 dark grey. And since we don't need shelves or anything beyond the two drop downs, just having minimal floating UI elements with the card spread front and center would be nice.

**Comment by mcorrell** [comment]
One issue: the "cover" card is rotated 90 degrees, so the tooltip ends up being rotated also...

**Comment by mcnuttandrew** [comment]
Closing, as I believe this all now works as desired
