### ISSUE TITLE
Additional spreads

### ISSUE THREAD

**Issue by mcnuttandrew** [mcorrell/vis-tarot#15]
More spreads = More fun 

This [resource](https://www.learnreligions.com/tarot-card-spreads-2562807) lists several additional spreads:

- Seven card Horseshoe spread
- Pentagram spread
- Romany Spread

I think it might be good to do those first two? The last one seems a little large for computer screen

**Comment by mcorrell** [comment]
In attempting to make the descriptions more descriptive, I clobbered whatever makes your single card spread work. Will revert tomorrow.

**Comment by mcnuttandrew** [comment]
I fixed the clobbering of the one card, but also the one card isn't that important?

**Comment by mcnuttandrew** [comment]
I'm satisfied by where we landed on this one
