### ISSUE TITLE
More example datasets

### ISSUE THREAD

**Issue by mcnuttandrew** [mcorrell/vis-tarot#17]
Maybe two more?

**Comment by mcorrell** [comment]
Added a school district datasource that has some interesting things in it. I might throw in ol' world indicators as well. Those + NBA + dairy I think should be plenty.

**Comment by mcorrell** [comment]
Oh man except IIB just released this: https://twitter.com/infobeautiful/status/1212779350631866368

**Comment by mcorrell** [comment]
Hmmm, world indicators seems to not work correctly (getting errors about boxplots etc). The others seem to work fine, though.

**Comment by mcnuttandrew** [comment]
The world indicators problem should be addressed in #28

**Comment by mcorrell** [comment]
Are there linting issues that are represented in #28 that aren't covered in .eslintrc ?

**Comment by mcnuttandrew** [comment]
i dunno most of those changes were generated automatically by prettier which is configured in the .prettierrc file?

**Comment by mcnuttandrew** [comment]
I think this is resolved now!
