### ISSUE TITLE
Write the daggum paper

### ISSUE THREAD

**Issue by mcorrell** [mcorrell/vis-tarot#20]
I will take a pass on this this afternoon + tomorrow, will ping folks where I think it needs TLC

**Comment by amcrisan** [comment]
@mcorrell  do you mind updating the major arcana figure on your end? Card 11 should have said "Quality" and not "missingness". I assume you've got a file somewhere...

**Comment by mcnuttandrew** [comment]
@amcrisan i made that figure! issue addressed

**Comment by mcnuttandrew** [comment]
@amcrisan do you want a figure that shows each of the spreads that feature?

**Comment by mcorrell** [comment]
Not certain if we'll have space... maybe just the celtic cross is the one to feature in the paper (I want to keep the major arcana as a full page figure and the intro + refs already puts up pretty much to the halfway point even with mostly empty sections).

**Comment by mcnuttandrew** [comment]
something i've been wondering about it is if we should introduce the term "v-hacking machine" here. we threw it around a bunch during the mirage paper but didn't actually end up using it, and it seems like this might be an appropriate venue?

**Comment by mcorrell** [comment]
There's room for it (I already talk about the Pi & Kay p-hacking machines stuff a little in my notes) but it feels a little weird to reference the mirage paper for this, since it will technically be a concurrent submission

**Comment by mcnuttandrew** [comment]
sorry i worded that poorly: i don't mean to reference the mirage paper. Instead introduce the v-hacking term here, it was a cool idea and we didn't get to use it. This seems like a good venue to introduce that term?

**Comment by amcrisan** [comment]
@mcorrell, @mcnuttandrew  wrapped up the first pass of the system design. Feel free to modify / shorten. Also @mcorrell I think you might have a different writing style than I do so feel free to modify according to tone and voice (and I suspect level of detail).

**Comment by mcnuttandrew** [comment]
I've spent a little time reviewing the paper this morning. I really like where it's going!

- Inconsistent minor/major arcana capitalization 
- I'm worried the tone is not satirical enough. In comparison with the bob ross paper, this paper feels like it takes itself pretty seriously. I don't know alt chi incredibly well, so if this type of tone flies then great! I just wanted to raise a concern
- is there going to be room for comments about how we'll present the work?

**Comment by mcorrell** [comment]
Yes, there's an explicit section in pcs for talking about the presentation.

I can make it more satirical also. I need to reread the séance paper to see what kind of tone they took, that might be a better model than Bob Ross

Also the deadline is noon Pacific tomorrow, so I will try to put the paper to bed tonight. We can keep tweaking the system past the deadline, but I think we mostly have everything we need for the writeup.

**Comment by mcorrell** [comment]
Also the margin figures appear to just totally wreck with the breaks in the paper and I have no idea what magic incantation in TeX fixes that.

**Comment by mcnuttandrew** [comment]
I was playing with that this morning, you just gotta shuffle em around until it works right :(

**Comment by mcorrell** [comment]
Current paper TODOS:

- [x] Code sanity check: assurance that the system does close enough to what we claim that it does that we can use it to write a case study
- [x] Minor arcana figure
- [x] Case study: a simple work through of, say, a three-card spread on a dataset, with special indications of what other paths might have been seen
- [x] A conclusion section
- [x] A sanity check pass for typos/missing content/placeholders etc.

**Comment by mcnuttandrew** [comment]
Dont forget a little section descibing how we'll present it maybe!

**Comment by mcorrell** [comment]
That goes in PCS rather than the paper proper, but point taken.

**Comment by mcnuttandrew** [comment]
I suspect "Code sanity check" is done, but i can't really tell i'm maybe too close to it

**Comment by mcorrell** [comment]
Let me try rolling the dice a few times on a case study and see what happens. We can always come back to clean up the code/UX later, but for now the priority is that the system does what we say it does (which it currently appears to).

**Comment by mcnuttandrew** [comment]
i did a google-doc based spell check, and looked pretty hard for placeholders. It doesn't mean their aren't any, but at the very least those checks passed?

**Comment by mcorrell** [comment]
Finishing up the case study now (I got _extremely_ lucky with a three-card draw for world indicators; it even meshes well with the mirage work, so I'm just going to go with a real draw here rather than reroll until I get something more dramatic), and made some tweaks to the conclusion.

When that's done I'll do a full pass, submit what's there as a just-in-case version, and go to bed. And if folks have more edits we can take things up again in the morning.
