### ISSUE TITLE
minor arcana suit svg

### ISSUE THREAD

**Issue by mcnuttandrew** [mcorrell/vis-tarot#34]
I think it would be good to have a pictoral image of the suit for each of the minor arcana (wands, pentacles, swords, cups). @amcrisan could you check in some appropriate ones from the noun project? 

I think it also might be good to have a full size button for the cards? To this end could you grab this guy https://thenounproject.com/search/?q=fullsize&i=1812632

**Comment by amcrisan** [comment]
@mcnuttandrew  added minor arcana images to assets, also added the full size button image too.
