### ISSUE TITLE
UI bugs, fixes, and nice-to-haves

### ISSUE THREAD

**Issue by mcorrell** [mcorrell/vis-tarot#37]
- [x] the resize button current just moves the cards to the next slot in the spread rather than making them larger

- [x] the cards disappear whenever the window size is changed and must be redealt

- [x] The sword svg is broken

- [x] The resize button could probably just appear on hover; it makes the cards a little crowded when it's always visible

- [x] The cards and UI could stand to have a little more padding/margins around them so there's a little more whitespace and the text is easier to read.

**Comment by mcnuttandrew** [comment]
#36 addressed the Sword svg problem and improved the white space stuff

**Comment by mcorrell** [comment]
I fixed the sword svg by changing the filename to "swords" in a push to main; does you PR fix it in a different way?

**Comment by mcnuttandrew** [comment]
Very very slightly, i over-rode your change with an updated version of the svg. There was a little bit of white space in the noun project icons so i imported them into sketch and re-exported them.
