### ISSUE TITLE
About button

### ISSUE THREAD

**Issue by mcnuttandrew** [mcorrell/vis-tarot#39]
It might be good to add an "About" modal or button or something to inform the random user who stumbles onto the app what the project is all about.

**Comment by mcorrell** [comment]
I was just thinking about that. That modal should probably also let people know what the affordances of the tool are (do we say anywhere that you click the deck to deal cards, for instance?)

**Comment by mcnuttandrew** [comment]
I think adding a "click to draw label" is just a good idea in general, i'll staple that on to my UI issues pr

**Comment by mcorrell** [comment]
Addressed in #46, closing
